### ISSUE TITLE
Postfix dashboard support to monitor queue

### ISSUE THREAD

**Issue by codyprashant** [eldada/postfix-relay-kubernetes#6]
I have been thinking if there is any way after deploying pods to monitor the postfix queue using some dashboard or any other ways  like using graffana or kibana.

**Comment by eldada** [comment]
For this, I guess you'd need to deploy a `Prometheus postfix exporter`...
I didn't try. Searching around there are a few examples online. You are welcome to try and share your experience.

**Comment by codyprashant** [comment]
Thanks.. I will try and let you know guys my experience
