### ISSUE TITLE
LoadBalancer service IP enhancement

### ISSUE THREAD

**Issue by icebrian** [eldada/postfix-relay-kubernetes#9]
I added to your service.yaml on line 11 the following:

```
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
```

Reason simply because I wanted to use a LoadBalancer type service and set a specific IP.

In the meantime thanks for this, very useful! :)

**Comment by eldada** [comment]
Cool. Thanks @icebrian. Do you want to suggest a pull request on this?

**Comment by eldada** [comment]
I already create the PR (I was doing some updates on the repo anyway...). Can you review and confirm this is what you meant?

**Comment by icebrian** [comment]
> I already create the PR (I was doing some updates on the repo anyway...). Can you review and confirm this is what you meant?

Confirmed! Thanks! :)
